services:
  hbase:
    image: harisekhon/hbase:latest
    container_name: hbase
    hostname: hbase
    ports:
      - "9090:9090"
      - "16000:16000"
      - "16010:16010"
      - "16020:16020"
      - "16030:16030"
      - "2181:2181"
    environment:
      - HBASE_CONF_hbase_cluster_distributed=false
    volumes:
      - hbase_data:/hbase-data
    restart: unless-stopped

volumes:
  hbase_data: